# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# https://github.com/marketplace/actions/deploy-github-pages-site

name: Deploy GitHub Pages

on: [push]
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
#        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./template-app/package-lock.json"
    - run: npm ci --prefix ./template-app
    - run: npm run build --if-present --prefix ./template-app -- --base-href /${{ github.event.repository.name }} --deploy-url /${{ github.event.repository.name }}/
#    - run: npm test
    - uses: actions/upload-artifact@v4
      with:
        name: pages
        path: template-app/dist/template-app/browser
        if-no-files-found: error

#  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: pages
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v3
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
